### ISSUE TITLE
Could you make a tag?

### ISSUE THREAD

**Issue by jcccn** [SmallSharpToolsOpenSource/PhotoZoom#2]
Glad to find you repo.

Could you make a tag, so that i can push it to CocoaPods?

Thank you!

**Comment by brennanMKE** [comment]
Make a tag?

**Comment by wjcoder** [comment]
Hello

Would you please how to integrate this into my project?
I placed UIScrollView and changed the class as PZPagingScrollView in storyboard
and set the pagingViewDelegate

and implemented these codes
- (Class)pagingScrollView:(PZPagingScrollView *)pagingScrollView classForIndex:(NSUInteger)index {
  // all page views are photo views
  return [PZPhotoView class];
  }
- (NSUInteger)pagingScrollViewPagingViewCount:(PZPagingScrollView *)pagingScrollView {
  return 1;
  }
- (UIView *)pagingScrollView:(PZPagingScrollView *)pagingScrollView pageViewForIndex:(NSUInteger)index {
  PZPhotoView *photoView = [[PZPhotoView alloc] initWithFrame:self.view.bounds];
  photoView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  photoView.photoViewDelegate = self;
  
  return photoView;
  }
- (void)pagingScrollView:(PZPagingScrollView *)pagingScrollView preparePageViewForDisplay:(UIView *)pageView forIndex:(NSUInteger)index {
  NSAssert([pageView isKindOfClass:[PZPhotoView class]], @"Invalid State");
  
  PZPhotoView *photoView = (PZPhotoView *)pageView;
  [photoView displayImage:[UIImage imageWithData:[[SBFileManager sharedManager] loadFile:self.snap.snapId type:self.snap.mediaType]]];
  }

but strange nothing is shown. what did I do wrongly?
